export const socketEvents = {
  presencePing: 'presence_ping',
  presenceAck: 'presence_ack',
  presenceSnapshot: 'presence_snapshot',
  channelPresenceSnapshot: 'channel_presence_snapshot',
  channelPresenceJoin: 'channel_presence_join',
  channelPresenceLeave: 'channel_presence_leave',
  joinChannelError: 'join_channel_error',
  leaveChannelError: 'leave_channel_error',
  userStatusChange: 'user_status_change',
  joinChannel: 'join_channel',
  requestServerMembers: 'request_server_members',
  serverMembersSnapshot: 'server_members_snapshot',
  serverMembersError: 'server_members_error',
  serverUnread: 'server_unread',
  serverUnreadCounts: 'server_unread_counts',
  mention: 'mention',
  directMessage: 'direct_message',
  serverInvite: 'server_invite',
  rtcJoinRoom: 'rtc:joinRoom',
  rtcCreateTransport: 'rtc:createTransport',
  rtcConnectTransport: 'rtc:connectTransport',
  rtcProduce: 'rtc:produce',
  rtcConsume: 'rtc:consume',
  rtcPauseConsumer: 'rtc:pauseConsumer',
  rtcResumeConsumer: 'rtc:resumeConsumer',
  rtcTransportDefaults: 'rtc:transport-defaults',
  rtcNewProducer: 'rtc:newProducer',
  producerClosed: 'producerClosed',
  p2pJoin: 'p2p:join',
  p2pSignal: 'p2p:signal',
  p2pPeerJoined: 'p2p:peer-joined',
  p2pPeerLeft: 'p2p:peer-left',
};

export type SocketEventKey = keyof typeof socketEvents;
